apiVersion: apps/v1  # Version of the Kubernetes API
kind: Deployment  # Specifies that this is a Deployment object
metadata:
  name: finance-deployment  # Name of the Deployment
  labels:
    app: finance  # Labels to identify the Deployment
spec:
  replicas: 3  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: finance  # Pods with this label will be managed by this Deployment
  template:
    metadata:
      labels:
        app: finance  # Labels for the Pod
    spec:
      containers:
      - name: finance  # Name of the container
        image: finance_tracker:0.0.53
        
---
apiVersion: v1  # Version of the Kubernetes API
kind: Service  # Specifies that this is a Service object
metadata:
  name: finance-service  # Name of the Service
spec:
  type: 
  selector:
    app: finance  # Target Pods with the label app: nginx
  ports:
    - protocol: TCP
      port: 8080  # Expose port 8080 for external traffic
      targetPort: 5000  # Redirect traffic to port 80 of the container
