apiVersion: apps/v1  # Version of the Kubernetes API
kind: Deployment  # Specifies that this is a Deployment object
metadata:
  name: category-deployment  # Name of the Deployment
  labels:
    app: category  # Labels to identify the Deployment
spec:
  replicas: 3  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: category  # Pods with this label will be managed by this Deployment
  template:
    metadata:
      labels:
        app: category  # Labels for the Pod
    spec:
      containers:
      - name: category  # Name of the container
        image: mohammadgh99/finance_tracker_category_service:0.0.53
        
---
apiVersion: v1  # Version of the Kubernetes API
kind: Service  # Specifies that this is a Service object
metadata:
  name: category-service  # Name of the Service
spec:
  type: 
  selector:
    app: category  # Target Pods with the label app: nginx
