apiVersion: apps/v1  # Version of the Kubernetes API
kind: Deployment  # Specifies that this is a Deployment object
metadata:
  name: reports-deployment  # Name of the Deployment
  labels:
    app: reports  # Labels to identify the Deployment
spec:
  replicas: 3  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: reports  # Pods with this label will be managed by this Deployment
  template:
    metadata:
      labels:
        app: reports  # Labels for the Pod
    spec:
      containers:
      - name: reports  # Name of the container
        image: mohammadgh99/finance_tracker_reports_service:0.0.53
        
---
apiVersion: v1  # Version of the Kubernetes API
kind: Service  # Specifies that this is a Service object
metadata:
  name: reports-service  # Name of the Service
spec:
  type: 
  selector:
    app: reports  # Target Pods with the label app: nginx
